---
# This collection is initialized by https://github.com/ansible/ansible-creator 24.12.1

# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: "cyberark"
name: "isp"
version: 1.0.5
readme: README.md
authors:
  - "@cyberark-bizdev"
  - "@nitsan-tzur"
  - "@compostCY"
description: "This is a Collection of the CyberArk ISP Ansible Security Automation toolkit."
license: [Apache-2.0]
tags:
    - cyberark
    - access
    - security
    - account
    - epv
    - vault
    - identity
    - credential
    - secret
    - privileged
dependencies: {}

repository: "https://github.com/cyberark/ansible-isp-collection"
issues: https://github.com/cyberark/ansible-isp-collection/issues
documentation: https://github.com/cyberark/ansible-isp-collection/README.md
homepage: https://www.cyberark.com

# A list of file glob-like patterns used to filter any files or directories that should not be included in the build
# artifact. A pattern is matched from the relative path of the file or directory of the collection directory. This
# uses 'fnmatch' to match the files or directories. Some directories and files like 'galaxy.yml', '*.pyc', '*.retry',
# and '.git' are always filtered. Mutually exclusive with 'manifest'
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
# A dict controlling use of manifest directives used in building the collection artifact. The key 'directives' is a
# list of MANIFEST.in style
# L(directives,https://packaging.python.org/en/latest/guides/using-manifest-in/#manifest-in-commands). The key
# 'omit_default_directives' is a boolean that controls whether the default directives are used. Mutually exclusive
# with 'build_ignore'
# manifest: null
